mod 'boxen',    '3.7.0', :github_tarball => 'boxen/puppet-boxen'
mod 'homebrew', '1.9.5', :github_tarball => 'boxen/puppet-homebrew'
mod 'stdlib',   '4.2.1', :github_tarball => 'puppetlabs/puppetlabs-stdlib'
mod 'xquartz',  '1.2.1', :github_tarball => 'boxen/puppet-xquartz'
